name: GitHub Actions Demo


run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - run: echo "Hello World"
      - run: |
          mkdir testFolder
          cd testFolder
          touch testFile.txt
          echo "this is a new file" > testFile.txt
      - run: |
          mkdir vasilis
          touch babis.txt
          echo "mamamamamafddfw" > babis.txt
          
